<?php
$ves = $this->helper('Ves\Themesettings\Helper\Theme');
$max_width = $ves->getGeneralCfg("general_settings/max_width");
$max_width_custom = $ves->getGeneralCfg("general_settings/max_width_custom");
$paneltool = $ves->getGeneralCfg("general_settings/paneltool");
?>
<?php if($paneltool){ ?>
<style type="text/css">
<?php
// LAYOUT
if($max_width && $max_width){ ?>
.navigation, .page-header .header.panel, .header.content, .footer.content, .page-wrapper > .widget, .page-wrapper > .page-bottom, .block.category.event, .top-container, .page-main {
<?php if($max_width == 'custom'){ ?>
max-width: <?php echo $max_width_custom; ?>;
<?php }else{ ?>
max-width: <?php echo $max_width; ?>;	
<?php } ?>
}
<?php } ?>
</style>
<?php } ?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cacheManager = $objectManager->create('Magento\Framework\App\Cache\Manager');
$cacheManager->flush($cacheManager->getAvailableTypes());

     

    $catalogSession = $objectManager->get('\Magento\Catalog\Model\Session');

    //$catalogSession->setMyName('Test');

    echo $catalogSession->getMyName();
// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
  $date = $objDate->gmtDate();
 $date2 = explode(' ', $date); 
 $testdate = $date2[0];
  $session_date = $date2[1];

 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $coreSession = $objectManager->get('Magento\Framework\Session\SessionManagerInterface'); 
  $coreSession->start();
  $getting_val =  $coreSession->getData('sidepart', array());
 // print_r($getting_val); 
  if($getting_val){
    $product_price = $getting_val[1];
    $session_time = $getting_val[4];
}
//     echo $product_Id;
//     echo $product_price;
      $session_time;
 //echo "string";
// echo time();

if($getting_val){
  if ($session_date > $session_time) {
   $coreSession->unset();
    $coreSession->destroy();
     // echo "---Session unset---";
 }else{
   // echo "---session set---";
 }  
}
 
?>
<script type="text/javascript">
     require(['jquery'],function($){
     jQuery(document).ready(function() {
    //     var price = '<?php $product_price; ?>';
    // jQuery(".product-item-info .price").text("£"+price);
});
    });
</script>