<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount" id="block-discount" style="display:none">
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Apply Discount Code') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?php if($block->getCouponCode()):
            strlen($block->getCouponCode()) ? ' applied' : ''; endif;?>">
                <?php if(empty($block->getCouponCode())): ?>
                    <input type="hidden" name="remove" id="remove-coupon" value="0" />
                    <div class="field">
                        <label for="coupon_code" class="label"><span><?php /* @escapeNotVerified */ echo __('Enter discount code') ?></span></label>
                        <div class="control">
                            <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?php echo $block->escapeHtml(__('Enter discount code'));?>" />
                        </div>
                    </div>
                <?php else : ?>
                    <div style="margin-right:10px;padding: 5px;background: #FFFACD;color: green;">
                        <span class="coupon success">Coupon Applied successfully</span>
                    </div>
                <?php endif; ?>
                <div class="actions-toolbar">
                    <?php if (empty($block->getCouponCode())): ?>
                    <div class="primary">
                        <button class="action apply primary" type="button" value="<?php /* @escapeNotVerified */ echo __('Apply Discount') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Apply Discount') ?></span>
                        </button>
                    </div>
                    <?php else: ?>
                        <div class="primary">
                            <button  type="button" class="action cancel primary" value="<?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?>"><span><?php /* @escapeNotVerified */ echo __('Cancel Coupon') ?></span></button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
    </div>
</div>
<?php if ($block->getCouponCode() && strlen($block->getCouponCode())) : ?>
<script>
    require([
        'jquery'
    ], function($) {
        $(function() {
            $(document).ready(function() {

                //DOM manipulation code
                console.log($('hemant'));
                setTimeout(function(){
                    if ($('#cart-totals .totals .discount.coupon').html() != "<?php echo $block->getCouponCode(); ?>") {
                        location.reload();
                    }
                }, 8000);
            });
        });
    });
</script>
<?php endif; ?>