<?php /** @var $this \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Type\Text */ ?>
<script id="custom-option-text-type-template" type="text/x-magento-tmpl">
    <div id="product_option_<%- data.option_id %>_type_<%- data.group %>" class="fieldset">
        <table class="data-table" cellspacing="0">
            <thead>
            <tr>
                <th class=""><?php echo __('Id') ?></th>               
                <?php if ($this->getCanReadPrice() !== false) : ?>
                <th class="type-price"><?php echo __('Price') ?></th>
                <th class="type-type"><?php echo __('Price Type') ?></th>
                <?php endif; ?>
                <th class="type-sku"><?php echo __('SKU') ?></th>
                <th class="type-last last"><?php echo __('Max Characters') ?></th>
            </tr>
            </thead>
            <tr>
                <td class="ox-opt-id">
                    <input data-form-part="product_form" id="ox_row_id_option_<%- data.option_id %>" name="product[options][<%- data.option_id %>][row_id]" type="hidden" value="<%- data.row_id %>">
                    <%- data.row_id %>
                </td>             
                <?php if ($this->getCanReadPrice() !== false) : ?>
                <td class="opt-price">
                    <input data-form-part="product_form" id="product_option_<%- data.option_id %>_price"
                           name="product[options][<%- data.option_id %>][price]"
                           class="input-text validate-number product-option-price"
                           type="text" value="<%- data.price %>" data-store-label="<%- data.price %>"
                        <?php if ($this->getCanEditPrice() === false) : ?>
                           disabled="disabled"
                        <?php endif; ?>>
                </td>
                <td class="opt-price-type"><?php echo $this->getPriceTypeSelectHtml('data-form-part="product_form"') ?><%= data.checkboxScopePrice %></td>
                <?php else : ?>
                <input data-form-part="product_form" id="product_option_<%- data.option_id %>_price" name="product[options][<%- data.option_id %>][price]" type="hidden">
                <input data-form-part="product_form" id="product_option_<%- data.option_id %>_price_type" name="product[options][<%- data.option_id %>][price_type]" type="hidden">
                <?php endif; ?>
                <td>
                    <input data-form-part="product_form" name="product[options][<%- data.option_id %>][sku]" class="input-text" type="text" value="<%- data.sku %>">
                </td>
                <td>
                    <input data-form-part="product_form" name="product[options][<%- data.option_id %>][max_characters]" class="input-text validate-zero-or-greater" type="text" value="<%- data.max_characters %>">
                </td>
            </tr>
        </table>
    </div>
</script>
