<?php
use Magento\Framework\App\Action\Action;
$image = $this->helper("\Ves\BaseWidget\Helper\Image");
$productlist_data = $this->helper('Ves\BaseWidget\Helper\Productlist');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imgHelper = $this->helper('Ves\BaseWidget\Helper\Image');
$_product = $this->getProduct();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

$addition_cls = $this->getData('addition_cls');
$title = $this->getData('title');
$background_color = $this->getData('background_color');
$color = '';

$style = '';


if($background_color != ''){
	$style .= 'background-color:'.$background_color.';';
}

/** THUMBNAIL **/
$imagesize = $this->getData('image_size');
$image_file = $this->getData('file');
$array_size = explode("x", $imagesize);
$image_width = isset($array_size[0])?(int)$array_size[0]:0;
$image_width = $image_width?$image_width: 0;
$image_height = isset($array_size[1])?(int)$array_size[1]:0;
$image_height = $image_height?$image_height: 0;
$thumbnailurl = "";
$show_countdowntimer =  $this->getData('show_timer_countdown');
if ($image_file && !preg_match("/^http\:\/\/|https\:\/\//", $image_file) && $image_width >0 && $image_height > 0) {
	$thumbnailurl = $image->resizeImage($image_file, (int)$image_width, (int)$image_height);
} else {
	$thumbnailurl = $this->getMediaUrl().$image_file;
}

if( $image_file != '' ){

    $position_x = 'left';
    if($this->getData('background_position_x') != ''){
        $position_x = $this->getData('background_position_x');
    }
    $position_y = 'center';
    if($this->getData('background_position_y') != ''){
        $position_y = $this->getData('background_position_y');
    }
    $style .= "background-image:url('".$thumbnailurl."');background-repeat: no-repeat;";
    $style .= 'background-position-x: '.$position_x.';';
    $style .= 'background-position-y: '.$position_y.';';
    $style .= 'float: right;width: 100%;';
}
if($style!='') $style = 'style="' . $style . '"';
$id = rand().time();
$productId = $id.$_product->getId();

$addToCartHtml = '<span'. __('Add to Cart').'</span>';
$wishlistHtml = '<span>'. __('Add to Wish List').'</span>';
$compareHtml = '<span>'. __('Add to Compare').'</span>';
//If exists ves themesettings
$ves = false;
$helper = $this->helper('Ves\BaseWidget\Helper\Data');
if($helper->checkModuleInstalled('Ves_Themesettings')) {
    $ves = $this->helper('Ves\Themesettings\Helper\Theme');
    $data = $this->helper('Ves\Themesettings\Helper\Data');
     //Addtocart
    $addtocart_popup_height = $ves->getProductListingCfg('product_settings/addtocart_popup_height');
    $addtocart_popup_width = $ves->getProductListingCfg('product_settings/addtocart_popup_width');
    $addtocart_format = $ves->getProductListingCfg('design/addtocart_format_type');
    $addtocart_text = $ves->getProductListingCfg('design/addtocart_format_text');
    $addtocart_class = $ves->getProductListingCfg('design/addtocart_format_class');
    $addtocartText = '<span>'.$addtocart_text.'</span>';
    $addtocartIcon = '<i class="'.$addtocart_class.'"></i>';
    $addToCartHtml = '';
    if((!$addtocart_format || $addtocart_format == 'text') && $addtocart_text){ // Only Text
        $addToCartHtml = $addtocartText;
    }elseif($addtocart_format == 'icon'){ // Only Icon
        $addToCartHtml = $addtocartIcon;
    }elseif($addtocart_format == 'icon-text'){ // Icon, Text
        $addToCartHtml = $addtocartIcon.$addtocartText;
    }elseif($addtocart_format == 'text-icon'){ // Text, Icon
        $addToCartHtml = $addtocart_text.$addtocartIcon;
    }
}
?>

<div class="ves-widget widget-singedeals block <?php echo $addition_cls; ?> " <?php echo $style; ?>>
	<?php if( $title != '' ){ ?>
	<div class="block-title">
		<strong><span><?php echo $title; ?></span></strong>
	</div>
	<?php } ?>
	<div class="widget-inner block-content single-deals">

		<?php if($_product != ''){ ?>
        <?php if(!$image_file) { ?>
        <?php
            $_image = $_imgHelper->getImg($_product, (int)$image_width, (int)$image_height, 'category_page_grid');
        ?>
        <?php if($_image){ ?>
        <div class="image col-lg-6 col-md-6 col-sm-4 col-xs-12">
            
            <a href="<?php echo $block->getSingleLink($_product) ?>" title="<?php echo $_image->getLabel() ?>" class="product-image img">
                
                <img class="img-responsive" src="<?php echo $_image->getUrl(); ?>" alt="<?php echo $_image->getLabel() ?>" />
            </a>
        </div>
        <?php } ?>
        <?php } ?>
        <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12 pull-right deal-product">
            <div class="product-shop product-block">
                <div class="f-fix">
                    <h3 class="deal-product-name"><a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('\Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>

                    <?php // Sale Icon, New Icon Block ?>
                    <?php
                    $show_new_label = $this->getData('show_new_label');
                    $show_sale_label= $this->getData('show_sale_label')
                    ?>
                    <?php if($show_new_label || $show_sale_label){ ?>
                    <div class="icon">
                        <?php
                        if($show_sale_label) {
                            $specialprice = $_product->getSpecialPrice();
                            $specialPriceFromDate = $_product->getSpecialFromDate();
                            $specialPriceToDate = $_product->getSpecialToDate();
                            $today =  time();
                            if ($specialprice) {
                                if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
                                    ?>
                                    <span class="onsale"><span><?php echo __("Sale");?></span></span>
                                    <?php
                                }
                            }
                        }
                        if($show_new_label) {
                            $is_new = $this->checkProductIsNew( $_product );
                            if($is_new) { ?>
                            <span class="new-icon"><span><?php echo __("New");?></span></span>
                            <?php
                        }
                    }
                    ?>
                </div>
                <?php } ?>

                <?php if ($this->getData('show_review')){ ?>
		<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php } ?>

		 <?php $shortDescription = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description'); ?>
                    <?php if ($this->getData('show_short_description') && $_product->getShortDescription() && $shortDescription!=''):?>

                        <div class="deal-short-description">
                            <?php $maxChar = $this->getData('short_max_char');
                            if(!is_numeric($maxChar)) $maxChar = 100;
                            ?>
                            <div class="std"><?php echo $this->subString($shortDescription, $maxChar); ?></div>
                        </div>
                    <?php endif;?>

                <?php
                if($this->getData('show_price')){
                    echo $block->getProductPrice($_product, '-widget-singedeals'.$id);
                }
                ?>

                <?php // Countdown Timer Block ?>
                <?php if( isset($_product) && $_product->getFinalPrice() < $_product->getPrice() && $show_countdowntimer && $_product->getSpecialToDate()!=''){
                    $date1 = date('G:i:s', strtotime($_product->getSpecialToDate()));
                    if ($date1 == "0:00:00") {
                        $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($_product->getSpecialToDate()));
                    }else{
                        $targetDate = date('m/d/Y G:i:s', strtotime($_product->getSpecialToDate()));
                    }
                    ?>
                    <div class="countdown-timmer productdeals">
                        <div class="item-detail">
                            <div class="timer-explain">(<?php echo date('m/d/Y', strtotime($_product->getSpecialToDate())); ?>)</div>
                        </div>
                        <div id="item-countdown-<?php echo $productId ?>" class="item-countdown"></div>
                        <script type="text/javascript">
                            require(['jquery',
                                    <?php if($productlist_data->isModuleEnabled('Ves_Productlist')){ ?>
                                    'Ves_Productlist/js/countdown'
                                    <?php } else { ?>
                                    'Ves_BaseWidget/js/countdown'    
                                    <?php } ?>
                                    ],function () {
                                    jQuery(document).ready(function(){
                                        jQuery("#item-countdown-<?php echo $productId ?>").lofCountDown({
                                            formatStyle:2,
                                            TargetDate:"<?php echo $targetDate; ?>",
                                            DisplayFormat:"<ul><li>%%D%% <div><?php echo __('Day');?></div></li><li> %%H%% <div><?php echo __('Hours');?></div></li><li> %%M%% <div><?php echo __('Mins');?></div></li><li> %%S%% <div><?php echo __('Secs');?></div></li></ul>",
                                            FinishMessage:"<?php echo __('Expired');?>",
                                        });
                                    });

                            });
                        </script>
                    </div>
                    <?php } ?>
                    <?php // End Countdown Timer Block ?>
                   
                   
			<div class="product-item product actions product-item-actions" style="display:block;">
				<div class="actions-primary">

				    <button class="action tocart primary"
				    data-mage-init='{"redirectUrl":{"url":"<?php echo $_product->getProductUrl(); ?>"}}'
				    type="button" title="<?php echo __('View & Buy') ?>">
				    <span><?php echo __('View & Buy') ?></span>
				    </button>
				</div>
			</div>	
</div>
</div>
<?php } ?>
</div>
</div>
</div>
