<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 

$customOptions = $_objectManager->get('Magento\Catalog\Model\Product\Option')->getProductOptionCollection($_product);

$it_works = False;
foreach($customOptions as $array) {
    if($array['default_title'] == 'Power' || $array['default_title'] == "Addition"|| $array['default_title'] == "Cylinder" || $array['default_title'] == "Diameter" || $array['default_title'] == "Dominance" || $array['default_title'] == "Basecurve") {
        $it_works = True;
        break;
    }
}






/*Code to Fetch the Attribute set Id & Name*/
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$attributeSet = $objectManager->create('Magento\Eav\Api\AttributeSetRepositoryInterface');
$attributeSetRepository = $attributeSet->get($_product->getAttributeSetId());
$attribute_set_name = $attributeSetRepository->getAttributeSetName();
/*code ends here*/
?>
<?php
$ves = $this->helper('Ves\Themesettings\Helper\Theme');
$show_addtocart = $ves->getProductPageCfg('element_settings/show_addtocart');
?>
<?php if($show_addtocart){ ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
             <?php if ($block->shouldRenderQuantity()): ?>

       <?php   if($it_works === True) { ?>

<?php }else{ ?>
   <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
             <div class="control">
                        <div class="quantity-adder">
                            <div class="quantity-number pull-left">
                                <input type="number"
                                name="qty"
                                id="qty"
                                maxlength="12"
                                value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                                title="<?php /* @escapeNotVerified */ echo __('Quantity') ?>" class="input-text qty"
                                data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                />
                            </div>
                            <div class="quantity-wrapper pull-left">
                                <span class="add-up add-action fa fa-plus" data-parentqty="true"></span>  
                                <span class="add-down add-action fa fa-minus" data-parentqty="true"></span>
                            </div>
                        </div>
                        <script type="text/javascript">
                            require(["jquery"], function(){
                                jQuery(window).ready( function(){
                                   jQuery(".quantity-adder .add-action").click( function(){
                                    if( jQuery(this).hasClass('add-up') ) {  
                                        jQuery(".quantity-adder .qty").val( parseInt(jQuery(".quantity-adder .qty").val()) + 1 );
                                    }else {
                                        if( parseInt(jQuery(".quantity-adder .qty").val())  > 1 ) {
                                            jQuery(".quantity-adder .qty").val( parseInt(jQuery(".quantity-adder .qty").val()) - 1 );
                                        }
                                    }
                                } );
                               })
                            });
                        </script>
                    </div>
        </div>
        <style type="text/css">
            #product-options-wrapper {
            display: none;
            }
        </style>
        <?php
} ?>

       
        <?php endif; ?>
            <?php //if ($block->shouldRenderQuantity()): ?>
		<!--Condition added for attribute set so that same code should run for default functionalities-->
		<?php // if($attribute_set_name != 'Contact_Lens' && $attribute_set_name != 'Contact_Lens_Coloured' && $attribute_set_name != 'Contact_Lens_Multifocal' && $attribute_set_name != 'Contact_Lens_Multifocal_Dominance' && $attribute_set_name != 'Contact_Lens_Toric'): ?>
                <!-- <div class="field qty">
                    <label class="label" for="qty" style="text-align: center;"><span><?php /* @escapeNotVerified */ //echo __('Qty') ?></span></label>
                    <div class="control">
                        <div class="quantity-adder">
                            <div class="quantity-number pull-left">
                                <input type="number"
                                name="qty"
                                id="qty"
                                maxlength="12"
                                value="<?php /* @escapeNotVerified */ //echo $block->getProductDefaultQty() * 1 ?>"
                                title="<?php /* @escapeNotVerified */ //echo __('Quantity') ?>" class="input-text qty"
                                data-validate="<?php //echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                />
                            </div>
                            <div class="quantity-wrapper pull-left">
                                <span class="add-up add-action fa fa-plus" data-parentqty="true"></span>  
                                <span class="add-down add-action fa fa-minus" data-parentqty="true"></span>
                            </div>
                        </div>
                        <script type="text/javascript">
                            require(["jquery"], function(){
                                jQuery(window).ready( function(){
                                   jQuery(".quantity-adder .add-action").click( function(){
                                    if( jQuery(this).hasClass('add-up') ) {  
                                        jQuery(".quantity-adder .qty").val( parseInt(jQuery(".quantity-adder .qty").val()) + 1 );
                                    }else {
                                        if( parseInt(jQuery(".quantity-adder .qty").val())  > 1 ) {
                                            jQuery(".quantity-adder .qty").val( parseInt(jQuery(".quantity-adder .qty").val()) - 1 );
                                        }
                                    }
                                } );
                               })
                            });
                        </script>
                    </div>
                </div> -->
		<?php //endif;?>
		<!--Code Ends here-->
            <?php //endif; ?>
            <div class="actions">
                <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"> 
                    <i class="fa fa-shopping-cart"></i> <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: true
                });
                widget.catalogAddToCart('submitForm', $(form));
                return false;
            }
        });
    });
</script>
<script>
 //    require(['jquery'],function($){    
 //    jQuery("#product-addtocart-button").click(function(){
 //        if(jQuery('#left_checked').not(':checked').length || jQuery('#right_checked').not(':checked').length){
        
 //            alert('Enter Your Prescription');
 //         }
 //         return false;
 //   });
 // });
</script>

<?php endif; ?>
<?php } ?>
