<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "optionExtended": {                 
                "spacer"     : "<?php echo $this->getViewFileUrl('Pektsekye_OptionExtended::images/spacer.gif') ?>",	
                "imageTitle" : "<?php echo $this->escapeJsQuote(__('Click to Enlarge')) ?>",
                "infoIcon"   : "<?php echo $this->getViewFileUrl('Pektsekye_OptionExtended::images/info_icon.gif') ?>",
                "checkIcon"  : "<?php echo $this->getViewFileUrl('Pektsekye_OptionExtended::images/check_icon.png') ?>",
                          
                "imageDirUrl"       : "<?php echo $this->getProductBaseMediaUrl() ?>",
                "thumbnailDirUrl"   : "<?php echo $this->getThumbnailDirUrl() ?>",
                "pickerImageDirUrl" : "<?php echo $this->getPickerImageDirUrl() ?>", 
                "hoverImageDirUrl"  : "<?php echo $this->getHoverImageDirUrl() ?>",              
                "placeholderUrl"    : "<?php echo $this->getPlaceholderUrl() ?>",
                	
                "inPreconfigured"   : <?php echo $this->getInPreconfigured() ?>,
           
                "config" : <?php echo $this->getConfig() ?>
            },
            "validation": {
                "ignore": ":hidden"
            }            
        }
    }
</script>
    
