<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block block-dashboard-orders">
<?php $_orders = $block->getOrders(); ?>
    <div class="block-title order">
        <strong><?php /* @escapeNotVerified */ echo __('Recent Orders') ?></strong>
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <a class="action view" href="<?php /* @escapeNotVerified */ echo $block->getUrl('sales/order/history') ?>">
                <span><?php /* @escapeNotVerified */ echo __('View All') ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block-content">
    <?php echo $block->getChildHtml()?>
    <?php if (sizeof($_orders->getItems()) > 0): ?>
        <div class="table-wrapper orders-recent">
            <table class="data table table-order-items recent" id="my-orders-table">
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Recent Orders') ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                        <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Ship To') ?></th>
                        <!-- <th scope="col" class="col total"><?php ///* @escapeNotVerified */ echo __('Order Total') ?></th> -->
                        <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                        <th scope="col" class="col actions"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($_orders as $_order): ?>
                        <tr>
                            <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?php echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                            <!-- <td data-th="<?php //echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ //echo $_order->formatPrice($_order->getGrandTotal()) ?></td> -->
                            <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action view">
                                    <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                                </a>
                                <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                    <a href="#" data-post='<?= /* @noEscape */
                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                            ->getPostData($block->getReorderUrl($_order))
                                        ?>' class="action order">
                                        <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                    </a>
                                <?php else: ?>    
                                    <a id="reorder-history-new" class="action re-order" data-id="<?php echo $_order->getId(); ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
                                    </a>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no orders.'); ?></span></div>
    <?php endif; ?>
    </div>
</div>
<div id="recent-reorder-popup" style="display: none;">
    <p> Dear Customer, <br/><br/> Due to Recent up-gradation on our platform all the previous orders are stored as information purpose only and you may not be able to reorder using the reorder button. <br/><br/>Please create a new order and all the future orders you can place using the reorder button. we sincerely apologies and are thankful to you for your understanding and support. </p>
</div>
<?php $myData = [
    'checkoutUrl' => $block->getUrl('checkout/cart/index'),
    'reorderUrl' => $block->getUrl('lens/manager/reorder')
]; ?>
<?php $serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($myData); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "lensReorder": <?php /* @noEscape */ echo $serializedFormData; ?>
        }
    }
</script>
<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ], function($, modal){
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: "Reorder Not Available", //write your popup title 
            buttons: [{
                text: 'OK',
                class: '',
                click: function() {
                    this.closeModal();
                }
            }]
        };

        //var popupdata = $('<div />').append($('#recent-reorder-popup'));
        modal(options, $('#recent-reorder-popup'));

        $('#reorder-recent-history').on('click', function() {
            $('#recent-reorder-popup').modal('openModal');
        });
    });
    
</script>