<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Subscriptions & Recurring Payments for Magento 2 (System)
 */
/** @var $block \Amasty\RecurringPayments\Block\Product\View\RecurringPayments */

$product = $block->getProduct();
?>

<?php if ($product->isSaleable() && $block->isRecurringEnable($product)): ?>
<div class="amrec-product-view">
    <?php if (!$block->isSubscriptionOnly($product)): ?>
        <div class="amrec-purchase-option">
            <input type="radio"
                   class="amrec-input -radio"
                   name="subscribe"
                   id="radio_purchase_once"
                   value="not_subscribe"
                   data-amrec-js="purchase-type"
                   data-validate="{'validate-one-required-by-name':true}"
                   data-errors-message-box="[data-amrec-js='validation-error']">
            <label for="radio_purchase_once"
                   class="amrec-label">
                <?= $block->escapeHtml($block->getSinglePurchaseLabel()) ?>
            </label>
        </div>
    <?php endif ?>
    <div class="amrec-purchase-option">
        <input type="radio"
               class="amrec-input -radio"
               name="subscribe"
               id="radio_subscribe_product"
               value="subscribe"
               data-amrec-js="purchase-type"
               data-validate="{'validate-one-required-by-name':true}"
               data-errors-message-box="[data-amrec-js='validation-error']"
               <?= $block->escapeHtml($block->isSubscriptionOnly($product) ? 'checked' : '') ?>>
        <label for="radio_subscribe_product"
               class="amrec-label">
            <?= $block->escapeHtml($block->getSingleRecurringLabel()) ?>
        </label>
        <div
            <?= !$block->isSubscriptionOnly($product) ? ' class="hidden"' : '' ?>
            data-amrec-js="recurring-settings"
            data-bind="scope: 'amasty-recurring-payments'" >
            <!-- ko template: getTemplate() --><!-- /ko-->
        </div>
    </div>
    <div data-amrec-js="validation-error"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app":  <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
<?php endif ?>
<script type="text/javascript">
require(["jquery"], function(jQuery) {
        jQuery(document).ready(function(){
        jQuery("#radio_purchase_once").click();
        });    
    });
</script>
<style>
    .amrec-subscription-info {
    display: none;
}
</style>