<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<?php $slash2 = '//'; ?>


<div class="social-links">
    <div style="padding-bottom:10px; color:red;"><?php if($_product->getId() == '4579'):?>Please note all images for illustrative purpose only and <br/> actual appearance may Vary <?php else: ?>Please note all images for illustrative purpose only<?php endif;?></div>
    <label style="text-align: left;width:40%;text-transform:uppercase;color:#000;font-weight:600;"><?php echo __('Share This') ?></label>
    <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
    <?php $_productName = urlencode(trim($_helper->productAttribute($_product, $_product->getName(), 'name')))?>
    <?php $_productImageUrl = urlencode(trim($this->helper('Magento\Catalog\Helper\Image')->init($_product, 'product_page_image_large')->getUrl()))?>
    <?php $_productUrl = urlencode(trim($_product->getProductUrl()))?>
    <?php $urlNew = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
    <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
             class="link-twitter" target="_blank" style="font-size:18px;color:#888;"><span><?php /* @escapeNotVerified */ echo __('Refer a friend') ?>
        </span>
    </a>

</div>
<div class="alo-social-links socials clearfix addit">
    <div class="custom-html">
        <h3 class="title-social"><?php /* @escapeNotVerified */ echo __('Share it:') ?></h3>
        <ul class="socials-share list-inline">
            <li class="facebook">
                <a class="trasition-all social-link facebook" title="<?php echo __('Share on Facebook') ?>" href="#" target="_blank" rel="nofollow" onclick="window.open('<?php echo $slash2 ?>www.facebook.com/sharer/sharer.php?u='+'<?php echo $_product->getProductUrl();?>&picture=<?php echo $_product->getImageUrl();?>');return false;"><em class="fa fa-facebook"><span class="hidden"><?php /* @escapeNotVerified */ echo __('facebook') ?></span></em>
                </a>
            </li>
            <li class="twitter">
                <a class="trasition-all social-link twitter" href="#" title="<?php echo __('Share on Twitter') ?>" rel="nofollow" target="_blank" onclick="window.open('<?php echo $slash2 ?>twitter.com/share?text=<?php echo $_product->getName();?>&amp;url=<?php echo $_product->getProductUrl();?>');return false;"><em class="fa fa-twitter"><span class="hidden"><?php /* @escapeNotVerified */ echo __('twitter') ?></span></em>
                </a>
            </li>
            <li class="pinterest">
                <a class="trasition-all social-link pinterest" href="#" title="<?php echo __('Pin this') ?>" rel="nofollow" target="_blank" onclick="window.open('<?php echo $slash2 ?>pinterest.com/pin/create/button/?url=<?php echo $_product->getProductUrl();?>&amp;media=http%3A%2F%2Fdemo.cactusthemes.com%2Fnewstube%2Fwp-content%2Fuploads%2F2015%2F06%2F014-Surf-woman.jpg&amp;description=<?php echo $_product->getName();?>');return false;"><em class="fa fa-pinterest"><span class="hidden"><?php /* @escapeNotVerified */ echo __('pinterest') ?></span></em>
                </a>
            </li>
            <li class="linkedin">
                <a class="trasition-all social-link linkedin" href="#" title="<?php echo __('Share on LinkedIn') ?>" rel="nofollow" target="_blank" onclick="window.open('<?php echo $slash2 ?>www.linkedin.com/shareArticle?mini=true&amp;url=<?php echo $_product->getProductUrl();?>&amp;title=<?php echo $_product->getName();?>');return false;"><em class="fa fa-linkedin"><span class="hidden"><?php /* @escapeNotVerified */ echo __('linkedin') ?></span></em>
                </a>
            </li>
        </ul>
    </div>
</div>
