<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <div class="contact-content row">
        <div class="contact-form clearfix">
			<div class="row">
			<div class="fix-width col-xs-12 col-sm-7 col-md-7">
			    <h3 class="page-subheading"><?php echo __('Contact Form') ?></h3>
				<p class="short-description"></p>
				<fieldset class="fieldset">
				 <div class="row">
				  <div class="col-lg-6 mb-3">
						<div class="field name required">
							<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
							<div class="control">
								<input placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?>" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
							</div>
						</div>
					</div>
					<div class="col-lg-6 mb-3">
						<div class="field email required">
							<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
							<div class="control">
								<input placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
							</div>
						</div>
					</div>
					<div class="col-lg-12">
					<div class="field telephone mb-3">
						<label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
						<div class="control">
							<input type="text" id="telephone" name="telephone" pattern="[7-9]{1}[0-9]{9}" title="Phone number with 7-9 and remaing 9 digit with 0-9" data-gtm-form-interact-field-id="0" class="valid" maxlength="10" required>
						</div>
					</div>
					<div class="field comment required mb-3">
						<label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
						<div class="control">
							<textarea placeholder="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
						</div>
					</div>
					<?php echo $block->getChildHtml('form.additional.info'); ?>
					<div class="actions-toolbar mt-4">
						<div class="primary">
							<input type="hidden" name="hideit" id="hideit" value="" />
							<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
								<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
							</button>
						</div>
					</div>
					</div>
					</div>
				</fieldset>
			</div>
			<div class="fix-width col-xs-12 col-sm-5 col-md-5">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_contact')->toHtml();?>
			</div>
		</div>	
		</div>
            <div class="fix-width col-xs-12 col-sm-6 col-md-6">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_map_contact')->toHtml();?>
			</div> 			
    	
    </div>
</form>
