<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$ves = $this->_ves;
$vesData = $this->_vesData;
$html = '';
$id = $block->getIdModifier() ? '-' . $block->getIdModifier() : time().rand();
?>

<!--<div class="header-links" id="header-links<?php echo $id?>">-->
    <div class="nav-menu" id="header-links<?php echo $id?>">
    <!--<div class="actions dropdown options header-links-options">-->
        <!--<div class="action toggle switcher-trigger" id="header-links-trigger<?php //echo $id?>">
            <i class="fa fa-user">&nbsp;</i> <strong class="hidden-xs"><?php //echo __('My Account') ?> </strong>
        </div>-->
        <ul class="ves-megamenu ves-horizontal nav-mobile">
        <?php
        foreach ($this->getLinks() as $link) {
                $html .= $this->renderLink($link);
        }
        echo $html;
        ?>
        
        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $custom_links =  $objectManager->get('Magento\Framework\Serialize\SerializerInterface')->unserialize($ves->getHeaderCfg('toplinks_settings/custom_links'));
        unset($custom_links['__empty']);
        foreach ($custom_links as $_link) { ?>
        <li class="<?php echo $_link['classes'] ?>  nav-item level0 nav-0 submenu-left subhover  dropdown level-top" >
            <a href="<?php echo $vesData->filter($_link['link']) ?>" target="<?php echo $_link['target'] ?>"><span></span><?php echo $_link['title'] ?></span></a>
        </li>
        <?php } ?>
        
    </ul>
<!--</div>-->
</div>




