<?php if ($this->canDisplay()): ?>
    <form method="POST" action="<?php echo $this->getSubmitUrl(); ?>" id="frm_products">
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>">
        <input type="hidden" name="order_id" value="<?php echo $this->currentOrderInProgress()->getId(); ?>">

        <table class="tbl-order">
            <tr>
                <th><?php echo __('Image'); ?></th>
                <th><?php echo __('Location'); ?></th>
                <th><?php echo __('Qty to ship'); ?></th>
                <th><?php echo __('Qty packed'); ?></th>
                <th><?php echo __('Sku'); ?></th>
                <th><?php echo __('Product'); ?></th>
                <th><?php echo __('Status'); ?></th>
            </tr>
            <?php foreach($this->getProducts() as $item): ?>
                <tr>
                    <td align="center"><img src="<?php echo $this->getProductImageUrl($item->getproduct_id()); ?>" width="50" height="50"></td>
                    <td align="center"><?php echo $this->getProductLocation($item->getproduct_id()); ?></td>
                    <td align="center">
                        <?php echo $item->getipi_qty(); ?>
                        <input type="hidden" id="qty_to_ship_<?php echo $item->getId(); ?>" value="<?php echo $item->getipi_qty(); ?>">
                        <input type="hidden" id="barcode_<?php echo $item->getId(); ?>" value="<?php echo $this->getBarcode($item->getproduct_id()); ?>">
                    </td>
                    <td align="center">
                        <input type="button" value="--" onclick="packingObj.qtyMin(<?php echo $item->getId(); ?>)" />
                        <input type="button" value="-"  onclick="packingObj.qtyDecrement(<?php echo $item->getId(); ?>)"/>
                        <input type="text" size="5" name="products[<?php echo $item->getipi_order_item_id(); ?>]" id="qty_packed_<?php echo $item->getId(); ?>" value="0">
                        <input type="button" value="+"  onclick="packingObj.qtyIncrement(<?php echo $item->getId(); ?>)"/>
                        <input type="button" value="++" onclick="packingObj.qtyMax(<?php echo $item->getId(); ?>)" />
                    </td>
                    <td><?php echo $item->getsku(); ?></td>
                    <td><?php echo $item->getname(); ?></td>
                    <td><div id="status_<?php echo $item->getId(); ?>"></div></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </form>
<?php endif; ?>